name: "Code Quality Checks"
description: "Run code quality checks including formatting, linting, and documentation"
runs:
  using: composite
  steps:
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install pre-commit
      shell: bash
      run: pip install pre-commit

    - name: Install SwiftFormat
      shell: bash
      run: brew install swiftformat

    - name: Run pre-commit hooks
      shell: bash
      run: pre-commit run --all-files

    - name: Check Swift formatting
      shell: bash
      run: |
        if command -v swiftformat &> /dev/null; then
          swiftformat --lint Sources/ Tests/
        else
          echo "SwiftFormat not installed, skipping format check"
        fi

    - name: Check for TODO/FIXME comments
      shell: bash
      run: |
        if grep -r "TODO\|FIXME" Sources/ Tests/; then
          echo "Found TODO/FIXME comments in code"
          exit 1
        fi

    - name: Check documentation coverage
      shell: bash
      run: |
        # Check that all public APIs have documentation comments
        find Sources/ -name "*.swift" -exec grep -l "public" {} \; | while read file; do
          if ! grep -q "///" "$file"; then
            echo "Warning: $file has public APIs but no documentation comments"
          fi
        done
