repos:
  # SwiftFormat for Swift code formatting
  - repo: https://github.com/nicklockwood/SwiftFormat
    rev: 0.54.0
    hooks:
      - id: swiftformat
        args: [--config, .swiftformat]
        files: \.(swift)$
        types: [text]
        additional_dependencies: []

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: debug-statements
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: mixed-line-ending
        args: [--fix, lf]

  # YAML formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [yaml]
        additional_dependencies: ['prettier@3.1.0']

  # Markdown formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types: [markdown]
        additional_dependencies: ['prettier@3.1.0']

  # Shell script formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types: [shell]
        additional_dependencies: ['prettier@3.1.0']

  # Security checks
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: |
          (?x)^(
              \.git/|
              \.build/|
              \.swiftpm/|
              \.index-build/|
              Tests/|
              doc/|
              \.github/
          )$ 