name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Swift
        uses: SwiftyLab/setup-swift@v1
        with:
          swift-version: "5.9"

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat

      - name: Install zlib using vcpkg
        run: .\vcpkg\vcpkg.exe install zlib:x64-windows

      - name: Set VCPKG environment variables
        run: |
          echo "VCPKG_ROOT=${{ github.workspace }}\vcpkg" >> $env:GITHUB_ENV
          echo "LIB=$env:GITHUB_WORKSPACE\vcpkg\installed\x64-windows\lib;$env:LIB" >> $env:GITHUB_ENV
          echo "INCLUDE=$env:GITHUB_WORKSPACE\vcpkg\installed\x64-windows\include;$env:INCLUDE" >> $env:GITHUB_ENV
          echo "PATH=${{ github.workspace }}\vcpkg\installed\x64-windows\bin;$env:PATH" >> $env:GITHUB_ENV

      - name: Build Swift project
        run: swift build -v

      - name: Run tests
        run: swift test -v
