name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  issues: read
  pull-requests: read

jobs:
  release:
    name: Create Release
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_15.2.app

      - name: Build and test
        run: |
          swift build
          swift test
          swift build -c release --product SwiftZlibCLI

      - name: Generate Release Notes
        id: release_notes
        run: |
          # Extract version from tag
          VERSION=${GITHUB_REF#refs/tags/}

          # Get commits since last tag
          if git describe --tags --abbrev=0 HEAD~1 >/dev/null 2>&1; then
            PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD~1)
            COMMITS=$(git log --oneline --no-merges $PREVIOUS_TAG..HEAD | head -20)
          else
            COMMITS=$(git log --oneline --no-merges | head -20)
          fi

          # Generate release notes
          cat << EOF > release_notes.md
          # SwiftZlib ${VERSION}

          ## What's Changed

          ### Features
          - Swift wrapper for zlib compression library
          - Cross-platform support (macOS, Linux)
          - Comprehensive API coverage (Data, String, File operations)
          - Async/Combine support for modern Swift concurrency
          - Streaming compression/decompression
          - Gzip file format support
          - Command-line interface with benchmarking
          - Performance profiling and optimization

          ### Bug Fixes
          - Fixed cross-platform random byte generation in CLI
          - Resolved debug output interference in tests
          - Corrected zlib dictionary inflation patterns

          ### Performance
          - Optimized memory usage with configurable levels
          - Efficient streaming for large files
          - Fast compression/decompression algorithms

          ### Documentation
          - Comprehensive API documentation
          - CLI usage examples and benchmarks
          - Architecture and testing guides

          ## Installation

          ```swift
          dependencies: [
              .package(url: "https://github.com/Kosikowski/swift-zlib.git", from: "$VERSION")
          ]
          ```

          ## Breaking Changes

          No breaking changes in this initial release.

          ## Recent Commits

          ```
          $COMMITS
          ```
          EOF

          echo "notes<<EOF" >> $GITHUB_OUTPUT
          cat release_notes.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: SwiftZlib ${{ github.ref_name }}
          body: ${{ steps.release_notes.outputs.notes }}
          draft: false
          prerelease: false
          generate_release_notes: false
