name: Windows Tests (Native Swift)

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test-windows-native:
    name: Windows (Native Swift 5.10.1)
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Visual Studio Build Tools
        uses: microsoft/setup-msbuild@v1

      - name: Install Swift
        run: |
          # Download Swift 5.10.1 for Windows
          $swiftVersion = "5.10.1"
          $swiftUrl = "https://download.swift.org/swift-${swiftVersion}-release/windows10/swift-${swiftVersion}-RELEASE-windows10.exe"
          $swiftInstaller = "swift-installer.exe"

          Write-Host "Downloading Swift ${swiftVersion}..."
          Invoke-WebRequest -Uri $swiftUrl -OutFile $swiftInstaller

          Write-Host "Installing Swift..."
          Start-Process -FilePath $swiftInstaller -ArgumentList "/S" -Wait

          # Add Swift to PATH
          $env:PATH = "C:\swift\bin;" + $env:PATH
          echo "C:\swift\bin" >> $env:GITHUB_PATH

          Write-Host "Swift installation completed"
        shell: pwsh

      - name: Install zlib via vcpkg
        run: |
          # Install vcpkg if not present
          if (-not (Test-Path "C:\vcpkg")) {
            git clone https://github.com/Microsoft/vcpkg.git C:\vcpkg
          }

          # Install zlib
          C:\vcpkg\vcpkg install zlib:x64-windows

          # Set environment variables
          $env:VCPKG_ROOT = "C:\vcpkg"
          echo "VCPKG_ROOT=C:\vcpkg" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Verify Swift installation
        run: |
          swift --version
          swift build --help
        shell: pwsh

      - name: Build and test
        run: |
          swift build
          swift test --parallel
        shell: pwsh

      - name: Run specific test groups
        run: |
          swift test --filter CoreTests
          swift test --filter ExtensionsTests
          swift test --filter FileOperationsTests
          swift test --filter ErrorHandlingTests
          swift test --filter StreamingTests
          swift test --filter ConcurrencyTests
        shell: pwsh

      - name: Build CLI tool
        run: |
          swift build --product SwiftZlibCLI
        shell: pwsh

  # Build verification - Windows Native
  build-verification-windows-native:
    name: Build Verification (Windows Native)
    strategy:
      matrix:
        configuration: [debug, release]
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Visual Studio Build Tools
        uses: microsoft/setup-msbuild@v1

      - name: Install Swift
        run: |
          $swiftVersion = "5.10.1"
          $swiftUrl = "https://download.swift.org/swift-${swiftVersion}-release/windows10/swift-${swiftVersion}-RELEASE-windows10.exe"
          $swiftInstaller = "swift-installer.exe"

          Invoke-WebRequest -Uri $swiftUrl -OutFile $swiftInstaller
          Start-Process -FilePath $swiftInstaller -ArgumentList "/S" -Wait

          $env:PATH = "C:\swift\bin;" + $env:PATH
          echo "C:\swift\bin" >> $env:GITHUB_PATH
        shell: pwsh

      - name: Install zlib via vcpkg
        run: |
          if (-not (Test-Path "C:\vcpkg")) {
            git clone https://github.com/Microsoft/vcpkg.git C:\vcpkg
          }
          C:\vcpkg\vcpkg install zlib:x64-windows
          $env:VCPKG_ROOT = "C:\vcpkg"
          echo "VCPKG_ROOT=C:\vcpkg" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Build and test package
        run: |
          swift build -c ${{ matrix.configuration }}
          swift test -c ${{ matrix.configuration }}
          swift build -c ${{ matrix.configuration }} --product SwiftZlibCLI
        shell: pwsh

  # Performance benchmarks - Windows Native
  benchmark-windows-native:
    name: Performance Benchmarks (Windows Native)
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Visual Studio Build Tools
        uses: microsoft/setup-msbuild@v1

      - name: Install Swift
        run: |
          $swiftVersion = "5.10.1"
          $swiftUrl = "https://download.swift.org/swift-${swiftVersion}-release/windows10/swift-${swiftVersion}-RELEASE-windows10.exe"
          $swiftInstaller = "swift-installer.exe"

          Invoke-WebRequest -Uri $swiftUrl -OutFile $swiftInstaller
          Start-Process -FilePath $swiftInstaller -ArgumentList "/S" -Wait

          $env:PATH = "C:\swift\bin;" + $env:PATH
          echo "C:\swift\bin" >> $env:GITHUB_PATH
        shell: pwsh

      - name: Install zlib via vcpkg
        run: |
          if (-not (Test-Path "C:\vcpkg")) {
            git clone https://github.com/Microsoft/vcpkg.git C:\vcpkg
          }
          C:\vcpkg\vcpkg install zlib:x64-windows
          $env:VCPKG_ROOT = "C:\vcpkg"
          echo "VCPKG_ROOT=C:\vcpkg" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Run performance tests
        run: |
          swift test --filter PerformanceTests --verbose
          swift test --filter 'testCompressionPerformance' --verbose
          swift test --filter 'testDecompressionPerformance' --verbose
          swift test --filter 'testMemoryEfficiency' --verbose
        shell: pwsh
